build:
  image: teaci/msys$$arch
  pull: true
  shell: msys$$arch
  commands:
    - if [ $$arch = 32 ]; then target=i686; fi
    - if [ $$arch = 64 ]; then target=x86_64; fi
    - pacman -S --needed --noconfirm --noprogressbar mingw-w64-${target}-pkg-config cmake python
    - git submodule update --init --recursive
    - wget https://bootstrap.pypa.io/get-pip.py
    - python get-pip.py
    - python --version
  - python setup.py build
    - python setup.py test

matrix:
  arch:
# Bug with 64-bit MSYS2 on WINE currently, disable temporarily.
#    - 64
    - 32
