version: '{build}'

os:
  - Visual Studio 2015
  - Visual Studio 2017

environment:
  matrix:
  - additional_flags: ""
  - additional_flags: "/std:c++latest"

matrix:
  exclude:
    - additional_flags: "/std:c++latest"
      os: Visual Studio 2015

init: []

install:
  - git submodule update --init --recursive

build_script: []

test_script:
  - python setup.py test
