version: '{build}'

os:
  - Visual Studio 2015
  - Visual Studio 2017

environment:
  matrix:
  - PYTHON: "C:\\Python34"
    PYTHON_VERSION: "3.4.x" # currently 3.4.3
    PYTHON_ARCH: "32"

  - PYTHON: "C:\\Python34-x64"
    PYTHON_VERSION: "3.4.x" # currently 3.4.3
    PYTHON_ARCH: "64"

init: []

install:
  - git submodule update --init --recursive
  - choco install -y swig
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - python --version

build_script:
  - python setup.py build_ext
  - python setup.py build

test_script:
  - python setup.py test
